import { FormEvent, useState } from "react";
import Editor from "@monaco-editor/react";
import { useNavigate } from "react-router-dom";
import { Wand2 } from "lucide-react";

import { getApiErrorMessage } from "../api/client";
import { generateReview } from "../api/reviews";
import { createSubmission } from "../api/submissions";
import { ErrorPanel } from "../components/ErrorPanel";
import { PageHeader } from "../components/PageHeader";

const languages = ["python", "typescript", "javascript", "java", "go", "rust", "csharp", "cpp"];

export function SubmitCodePage() {
  const navigate = useNavigate();
  const [language, setLanguage] = useState("python");
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    setIsSubmitting(true);

    try {
      const submission = await createSubmission({ language, code });
      const review = await generateReview(submission.id);
      navigate(`/reviews/${review.id}`);
    } catch (requestError) {
      setError(getApiErrorMessage(requestError));
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <>
      <PageHeader
        title="Code submission"
        description="Submit a code snippet and generate a structured AI review in one flow."
      />
      <form onSubmit={handleSubmit} className="grid gap-6 lg:grid-cols-[280px_1fr]">
        <aside className="rounded-md border border-slate-200 bg-white p-5 dark:border-ink-700 dark:bg-ink-900">
          <label className="block">
            <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Language</span>
            <select
              value={language}
              onChange={(event) => setLanguage(event.target.value)}
              className="mt-2 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20 dark:border-ink-700 dark:bg-ink-950"
            >
              {languages.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </select>
          </label>

          <button type="submit" className="primary-button mt-5 w-full justify-center" disabled={isSubmitting || !code.trim()}>
            <Wand2 size={18} />
            {isSubmitting ? "Reviewing..." : "Generate review"}
          </button>

          <p className="mt-4 text-sm text-slate-600 dark:text-slate-400">
            Reviews are generated by the configured backend AI provider.
          </p>
        </aside>

        <section className="space-y-4">
          {error ? <ErrorPanel message={error} /> : null}
          <div className="overflow-hidden rounded-md border border-slate-200 dark:border-ink-700">
  <Editor
    height="560px"
    language={language}
    theme="vs-dark"
    value={code}
    onChange={(value) => setCode(value || "")}
    options={{
      minimap: { enabled: false },
      fontSize: 14,
      automaticLayout: true,
      wordWrap: "on",
      scrollBeyondLastLine: false,
      tabSize: 2,
      lineNumbers: "on",
      formatOnPaste: true,
      formatOnType: true,
    }}
  />
</div>
        </section>
      </form>
    </>
  );
}
